version: '3.1'

services:

  my-mongodb:
    container_name: my-mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://my-mongodb:27017/
    depends_on:
      - my-mongodb

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001" 
    depends_on:
      - my-mongodb  

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  
    depends_on:
      - backend  


