version: '3.1'

services:

  my-mongodb:
    container_name: my-mongodb
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - my-mongo:/data/db
    networks:
    - m5md

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://my-mongodb:27017/
    volumes:
      - my-mongo:/data/db
    depends_on:
      - my-mongodb
    networks:
    - m5md

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001" 
    depends_on:
      - my-mongodb  
    networks:
    - m5md

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  
    depends_on:
      - backend  
    networks:
    - m5md

volumes:
  my-mongo:

networks:
  m5md:
    driver: bridge
